import React from 'react'
import './footer.scss'
const Footer = () => {
    return (
        <div className='footer'>
            <div className="container">
                <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum similique quos voluptatibus laborum veritatis officia illo asperiores dicta, et est aspernatur, aliquid ut maiores nostrum commodi doloribus vel harum? Molestiae, laboriosam placeat ipsum non animi dicta quos repudiandae architecto necessitatibus aliquam qui nesciunt autem, aliquid porro mollitia sed deleniti et id! Aperiam minima provident voluptatibus, ipsa mollitia ex corrupti maiores quidem libero amet adipisci odit consectetur doloremque ad doloribus et iure! Placeat, reprehenderit. Ratione assumenda dolor repellat blanditiis perferendis, ab et? Qui sint aut quos veniam rerum corporis non voluptatem? Illo eveniet quaerat itaque harum beatae tempora fugit vero odio.</h1>
                <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum similique quos voluptatibus laborum veritatis officia illo asperiores dicta, et est aspernatur, aliquid ut maiores nostrum commodi doloribus vel harum? Molestiae, laboriosam placeat ipsum non animi dicta quos repudiandae architecto necessitatibus aliquam qui nesciunt autem, aliquid porro mollitia sed deleniti et id! Aperiam minima provident voluptatibus, ipsa mollitia ex corrupti maiores quidem libero amet adipisci odit consectetur doloremque ad doloribus et iure! Placeat, reprehenderit. Ratione assumenda dolor repellat blanditiis perferendis, ab et? Qui sint aut quos veniam rerum corporis non voluptatem? Illo eveniet quaerat itaque harum beatae tempora fugit vero odio.</h1>
                <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum similique quos voluptatibus laborum veritatis officia illo asperiores dicta, et est aspernatur, aliquid ut maiores nostrum commodi doloribus vel harum? Molestiae, laboriosam placeat ipsum non animi dicta quos repudiandae architecto necessitatibus aliquam qui nesciunt autem, aliquid porro mollitia sed deleniti et id! Aperiam minima provident voluptatibus, ipsa mollitia ex corrupti maiores quidem libero amet adipisci odit consectetur doloremque ad doloribus et iure! Placeat, reprehenderit. Ratione assumenda dolor repellat blanditiis perferendis, ab et? Qui sint aut quos veniam rerum corporis non voluptatem? Illo eveniet quaerat itaque harum beatae tempora fugit vero odio.</h1>
                <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum similique quos voluptatibus laborum veritatis officia illo asperiores dicta, et est aspernatur, aliquid ut maiores nostrum commodi doloribus vel harum? Molestiae, laboriosam placeat ipsum non animi dicta quos repudiandae architecto necessitatibus aliquam qui nesciunt autem, aliquid porro mollitia sed deleniti et id! Aperiam minima provident voluptatibus, ipsa mollitia ex corrupti maiores quidem libero amet adipisci odit consectetur doloremque ad doloribus et iure! Placeat, reprehenderit. Ratione assumenda dolor repellat blanditiis perferendis, ab et? Qui sint aut quos veniam rerum corporis non voluptatem? Illo eveniet quaerat itaque harum beatae tempora fugit vero odio.</h1>
            </div>
        </div>
    )
}

export default Footer